version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/rabbitai-frontend/"
    schedule:
      interval: "daily"
    labels:
      - npm
      - dependabot

  - package-ecosystem: "pip"
    directory: "/requirements/"
    schedule:
      interval: "daily"
    labels:
      - pip
      - dependabot

  - package-ecosystem: "npm"
    directory: ".github/actions"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 0
