# https://cwiki.apache.org/confluence/display/INFRA/.asf.yaml+features+for+git+repositories
---
github:
  description: "Rabbitai is a Data Visualization and Data Exploration Platform"
  homepage: https://rabbitai.sgic.net.cn/
  labels:
    - rabbitai
    - apache
    - apache-rabbitai
    - data-visualization
    - data-viz
    - analytics
    - business-intelligence
    - data-science
    - data-engineering
    - asf
    - bi
    - business-analytics
    - data-analytics
    - data-analysis
    - data-science
    - python
    - react
    - sql-editor
    - flask
  features:
    # Enable issues management
    issues: true
    # Enable projects for project management boards
    projects: true
    # Enable wiki for documentation
    wiki: true

  enabled_merge_buttons:
    squash: true
    merge: false
    rebase: false

  protected_branches:
    master:
      required_status_checks:
        # strict means "Require branches to be up to date before merging".
        strict: false
        # contexts are the names of checks that must pass
        contexts:
          - check
          - cypress-matrix (1, chrome)
          - cypress-matrix (2, chrome)
          - cypress-matrix (3, chrome)
          - docker-build
          - frontend-build
          - pre-commit (3.7)
          - python-lint (3.7)
          - test-mysql (3.7)
          - test-postgres (3.7)
          - test-postgres (3.8)
          - test-sqlite (3.7)

      required_pull_request_reviews:
        dismiss_stale_reviews: false
        require_code_owner_reviews: true
        required_approving_review_count: 1

      required_signatures: false
