apiVersion: v1
kind: Secret
metadata:
  name: {{ template "rabbitai.fullname" . }}-config
  labels:
    app: {{ template "rabbitai.fullname" . }}
    chart: {{ template "rabbitai.chart" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
stringData:
  rabbitai_config.py: |
{{- include "rabbitai-config" . | nindent 4 }}
  rabbitai_init.sh: |
{{- tpl .Values.init.initscript . | nindent 4 }}
  rabbitai_bootstrap.sh: |
{{- tpl .Values.bootstrapScript . | nindent 4 }}

{{- if .Values.extraSecrets }}
{{- range $path, $config := .Values.extraSecrets }}
  {{ $path }}: |
{{- tpl $config $ | nindent 4 -}}
{{- end -}}
{{- end -}}
