apiVersion: v1
kind: Secret
metadata:
  name: {{ template "rabbitai.fullname" . }}-env
  labels:
    app: {{ template "rabbitai.fullname" . }}
    chart: {{ template "rabbitai.chart" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
stringData:
    REDIS_HOST: {{ tpl .Values.rabbitaiNode.connections.redis_host . | quote }}
    REDIS_PORT: {{ .Values.rabbitaiNode.connections.redis_port | quote }}
    DB_HOST: {{ tpl .Values.rabbitaiNode.connections.db_host . | quote }}
    DB_PORT: {{ .Values.rabbitaiNode.connections.db_port | quote }}
    DB_USER: {{ .Values.rabbitaiNode.connections.db_user | quote }}
    DB_PASS: {{ .Values.rabbitaiNode.connections.db_pass | quote }}
    DB_NAME: {{ .Values.rabbitaiNode.connections.db_name | quote }}
    {{- if .Values.extraSecretEnv }}
    {{- range $key, $value := .Values.extraSecretEnv }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
    {{- end }}
