apiVersion: v1
kind: Service
metadata:
  name: {{ template "rabbitai.fullname" . }}
  labels:
    app: {{ template "rabbitai.name" . }}
    chart: {{ template "rabbitai.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- with .Values.service.annotations }}
  annotations:
{{- toYaml . | nindent 4 }}
{{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ template "rabbitai.name" . }}
    release: {{ .Release.Name }}
  {{- if .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{- end }}
