QUERY_FORMAT = "?q={}"

DASHBOARDS_API_URL = "api/v1/dashboard/"
DASHBOARDS_API_URL_WITH_QUERY_FORMAT = DASHBOARDS_API_URL + QUERY_FORMAT
DASHBOARD_API_URL_FORMAT = DASHBOARDS_API_URL + "{}"
EXPORT_DASHBOARDS_API_URL = DASHBOARDS_API_URL + "export/"
EXPORT_DASHBOARDS_API_URL_WITH_QUERY_FORMAT = EXPORT_DASHBOARDS_API_URL + QUERY_FORMAT

GET_DASHBOARD_VIEW_URL_FORMAT = "/rabbitai/dashboard/{}/"
SAVE_DASHBOARD_URL_FORMAT = "/rabbitai/save_dash/{}/"
COPY_DASHBOARD_URL_FORMAT = "/rabbitai/copy_dash/{}/"
ADD_SLICES_URL_FORMAT = "/rabbitai/add_slices/{}/"

DELETE_DASHBOARD_VIEW_URL_FORMAT = "/dashboard/delete/{}"
GET_DASHBOARDS_LIST_VIEW = "/dashboard/list/"
NEW_DASHBOARD_URL = "/dashboard/new/"
GET_CHARTS_API_URL = "/api/v1/chart/"

GAMMA_ROLE_NAME = "Gamma"

ADMIN_USERNAME = "admin"
GAMMA_USERNAME = "gamma"

DASHBOARD_SLUG_OF_ACCESSIBLE_TABLE = "births"
DEFAULT_DASHBOARD_SLUG_TO_TEST = "births"
WORLD_HEALTH_SLUG = "world_health"
